config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'

  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]


  def show
  end

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    # raise 'error'
    if @task.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @task.update_attributes(task_params)
    redirect_to root_url
  end

  def destroy
    @task.destroy
    redirect_to root_url
  end





  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :category, :priority, :is_completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<ul class="nav nav-pills">
  <li role="presentation" class="active"><a href=<%= root_path %> >Temple Grounds</a></li>
  <li role="presentation"><a href= <%= new_task_path %> >Train</a></li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
      Temple Gates <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
      <li><a href="#">Train</a></li>
      <li><a href="#">Unfinished Tasks</a></li>
      <li><a href="#">Completed Tasks</a></li>
    </ul>
  </li>
  
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>

	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :category %>
	<%= f.text_field :category %>

	<%= f.label :priority %>
	<%= f.select :priority, [['High', 'high'], ['Medium', 'medium'], ['Low', 'low']] %>

	<%= f.label :is_completed %>
	<%= f.check_box :is_completed %>

<!-- 	<%= f.label :is_completed %>
	<%= f.text_field :is_completed %> -->

	<%= f.submit %>

<% end %>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>


<%= render 'form' %>

app/views/tasks/index.html.erb
<h2>Go young grasshopper.</h2> 
<p><%= link_to 'Go now', new_task_path %></p>

<ol>
	<h4>Your Tasks:</h4>	
	<% @tasks.each do |task| %>
		<div><li><p><em><%= task.title %></em> 

			<%= link_to 'Give up', task_path(task) , method: :delete, data: {confirm: 'Giving up already?'} %></p>
			</li>
			<ul>
				<li><p>Category: <%= task.category %> </p></li> 
				<li><p>Priority: <%= task.priority %> </p></li> 
				<li class='index_form'>  			
					<%= form_for(task) do |f| %>
						<%= f.check_box :is_completed %>
						<%= f.submit 'Complete?' %>
					

					
					<% end %></li> 
			</ul></div>
	<% end %>
</ol>

app/views/tasks/new.html.erb
<h1>New task</h1>


<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>